# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rishabh Garg
title: Web Developer
email: rishabhgargdps@gmail.com
website: rishabhgargdps/rishabhgargdps.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links 
github_username:  rishabhgargdps
stackoverflow_username: "15760258"
linkedin_username: rishabhgargbits
orcid_username: rishabhgargdps@gmail.com
twitter_username: rishabhgargdps

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Engineering second year student at BITS - Pilani, Goa, specialized in Deep Learning (Neural Networks), Applied Data   Science with Python, TensorFlow and Blockchain Technology. 
  Skilled in CSS, HTML and JavaScript Libraries, aiming to gain work experience as <mark>Full Stack Web Developer</mark>.

content:
  - title: Programming Languages, Tools and Technologies # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DSA
        description: | # this will include new lines to allow paragraphs
          Programming in C / C++, Python, R, MATLAB, Solidity and Pine Script
      - layout: left
        title: Web technologies and Frameworks
        description: | # this will include new lines to allow paragraphs
          HTML5.0, CSS3.0, Twitter Bootstrap, Javascript libraries
          - React
          - Vue
          - Angular
      - layout: left
        title: DBMS and ORM
        description: | # this will include new lines to allow paragraphs
          Comfortable in working with structured and unstructured data
          - SQL
          - MongoDB
      - layout: left
        title: Data Science and Machine Learning
        description: | # this will include new lines to allow paragraphs
          Data Science Libraries
          - Seaborn
          - Scikit Learn
          Deep Learning frameworks
          - Tensorflow
          Transfer Learning
          - VGG
          - ResNet
          - InceptionV3
      - layout: left
        title: Blockchain DApps development
        description: | # this will include new lines to allow paragraphs
          - Remix IDE
          - Truffle IDE
          - Metamask
      - layout: left
        title: Finance
        description: | # this will include new lines to allow paragraphs
          - Sustainable finance
          - Neurofinance
          - Portfolio Construction
          - Strategic and Tactical Asset allocation
          - Risk Management
  - title: Work-Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Internship at Mittal Institute
        link: https://mittalinstitute.org
        # link_text: boringcompany.com
        sub_title: Front-end Web developer
        caption: April 2020 - June 2020
        quote: >
          Used technologies such as React, npm, express and twitter bootstrap framework to optimize the user interface.
        description: | # this will include new lines to allow paragraphs
            Every company or college needs its website to be user friendly and hassle free. This project was intended to solve such problems.
      - layout: left
        title: Center for Technical Education
        link: bpgc-cte.org
        # link_text: boringcompany.com
        sub_title: Front-end Web developer
        caption: Aug 2019 - Present
        quote: >
          Used technologies such as React, npm, express and twitter bootstrap framework to optimize the user interface.
        description: | # this will include new lines to allow paragraphs
            Every company or college needs its website to be user friendly and hassle free. This project was intended to solve such problems.
      - layout: left
        title: Wallstreet Club
        link: facebook.com/wsc.bitsgoa/
        # link_text: boringcompany.com
        sub_title: Technical Analyst
        caption: Aug 2019 - Present
        quote: >
          Used technologies such as React, npm, express and twitter bootstrap framework to optimize the user interface.
        description: | # this will include new lines to allow paragraphs
            Every company or college needs its website to be user friendly and hassle free. This project was intended to solve such problems.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BITS Pilani, Goa
        caption: 2019 - 2023
        sub_title: B.E. Electronics and Communication Engineering
        quote: >
          I am an undergrad at BITS Pilani Goa Campus.
        description: | # this will include new lines to allow paragraphs
          CGPA: 9.23
          
          Relevant courses
          - CS
          - ECE
          - Finance
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amazon clone
        link: github.com/rishabhgargdps/amazon-clone
        # link_text: Project Website
        additional_links:
          - title:  rishabhgargdps/amazon-clone
            icon: fab fa-github
            url: github.com/rishabhgargdps/amazon-clone
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a full stack clone which contains all the functionality of the amazon interface including payments
        description: | # this will include new lines to allow paragraphs
          The framework used in the project is <mark>React</mark>
      - layout: left
        title: Pine script strategies
        link: github.com/rishabhgargdps/amazon-clone
        # link_text: Project Website
        additional_links:
          - title:  rishabhgargdps/amazon-clone
            icon: fab fa-github
            url: github.com/rishabhgargdps/amazon-clone
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a full stack clone which contains all the functionality of the amazon interface including payments
        description: | # this will include new lines to allow paragraphs
          The framework used in the project is <mark>React</mark>
      - layout: left
        title: Cryptocurrency prices
        link: github.com/rishabhgargdps/amazon-clone
        # link_text: Project Website
        additional_links:
          - title:  rishabhgargdps/amazon-clone
            icon: fab fa-github
            url: github.com/rishabhgargdps/amazon-clone
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is a full stack clone which contains all the functionality of the amazon interface including payments
        description: | # this will include new lines to allow paragraphs
          The framework used in the project is <mark>React</mark>
  - title: Specializations # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      Through Coursera
      - Applied Data Science with Python
        
        University of Michigan, US
      - Investment Management
        University of Geneva, Switzerland
      - Deep Learning
        Coursera - deeplearning.ai
      - Blockchain
        The State University of New York, US
      - TensorFlow in Practice
        deeplearning.ai
  - title: Online Courses # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      Through Coursera
      - Internet of Things
        Stanford University, US
      - Java for Android
        Vanderbilt University, US
      - Blockchain and Cryptocurrency
        University of Michigan, US
      - HTML, CSS and Javascript for WebD
        Johns Hopkins University, US
      - Big Data Analytics
        Griffith University, Australia
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BITS Pilani, Goa
        caption: 2019 - 2023
        sub_title: B.E. Electronics and Communication Engineering
        quote: > 
         
        description: | # this will include new lines to allow paragraphs
          CGPA: 9.23
          
          Relevant courses
          - CS
          - ECE
          - Finance
  - title: Presentations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BITS Pilani, Goa
        caption: 2019 - 2023
        sub_title: B.E. Electronics and Communication Engineering
        quote: > 
         
        description: | # this will include new lines to allow paragraphs
          CGPA: 9.23
          
          Relevant courses
          - CS
          - ECE
          - Finance
  - title: Hobbies and Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in web development and quantitative finance some of my other interests and hobbies are:
      - Creative writing
      - Public Speaking
      - Stock Trading
      - Astronomy
      - Chess
      - Digital Illustrations
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
